language: python
python:
  - "2.7"
  - "pypy"
  - "3.4"

before_install:
  - sudo apt-get install build-essential python-dev

install: pip install tox setuptools virtualenv --upgrade

env:
  - TOX_ENV=py27
  - TOX_ENV=pypy
  - TOX_ENV=py34
  - TOX_ENV=pep8

script: tox -v -e $TOX_ENV -- -v

notifications:
  email:
    - bm_witness@yahoo.com

