language: python
matrix:
    include:
        - python: "pypy3"
          env: TEST_SUITE=suite_pypy3 TOX_ENV=pypy3
        - python: "3.6"
          env: TEST_SUITE=suite_3_6 TOX_ENV=pep8
        - python: "3.6"
          env: TEST_SUITE=suite_3_6 TOX_ENV=docs
        - python: "3.5"
          env: TEST_SUITE=suite_3_5 TOX_ENV=py35
        - python: "3.7"
          env: TEST_SUITE=suite_3_7 TOX_ENV=py37
        - python: "3.8"
          env: TEST_SUITE=suite_3_8 TOX_ENV=py38
        - python: "3.6"
          env: TEST_SUITE=suite_3_6 TOX_ENV=py36
        - python: "3.6"
          env: TEST_SUITE=suite_3_6 TOX_ENV=py36-httpretty
        - python: "3.6"
          env: TEST_SUITE=suite_3_6 TOX_ENV=py36-requests-mock
        - python: "3.6"
          env: TEST_SUITE=suite_3_6 TOX_ENV=py36-responses
        - python: "2.7"
          env: TEST_SUITE=suite_2_7 TOX_ENV=py27
        - python: "2.7"
          env: TEST_SUITE=suite_2_7 TOX_ENV=py27-httpretty
        - python: "2.7"
          env: TEST_SUITE=suite_2_7 TOX_ENV=py27-requests-mock
        - python: "2.7"
          env: TEST_SUITE=suite_2_7 TOX_ENV=py27-responses
        - python: "pypy"
          env: TEST_SUITE=suite_pypy TOX_ENV=pypy

sudo: required
before_install:
  - sudo apt-get install build-essential python-dev

install: pip install tox setuptools virtualenv coveralls --upgrade

script: tox -v -e $TOX_ENV -- -v

after_success: coveralls

notifications:
  email:
    - bm_witness@yahoo.com

